---
- hosts: nodes
  gather_facts: no
  tasks:
#Install docker
   - debug: msg="{{ lookup('env','BUILD_TAG') }}"
#Look up for build tag var
   - include_role:
       name: docker-role
#Make first webapp container
   - include_role:
       name: web-app_role
       public: yes
     vars:
       docker_container_name: 'webapp1'
       docker_image_name: 'ffswhy1/flask_app'
       docker_image_build: '{{ BUILD_TAG }}'
       hostname: 'webapp1'
       src_port: 5001
#Make second webapp container
   - include_role:
       name: web-app_role
       public: yes
     vars:
       docker_container_name: 'webapp2'
       docker_image_name: 'ffswhy1/flask_app'
       docker_image_build: '{{ BUILD_TAG }}'
       hostname: 'webapp2'
       src_port: 5002
#Make third webapp container
   - include_role:
       name: web-app_role
       public: yes
     vars:
       docker_container_name: 'webapp3'
       docker_image_name: 'ffswhy1/flask_app'
       docker_image_build: '{{ BUILD_TAG }}'
       hostname: 'webapp3'
       src_port: 5003
#Make Nginx container
   - include_role:
       name: nginx-load_balancer
       public: yes
     vars:
       app_name: 'webapp'
       server1_url: 'webapp1:5000'
       server2_url: 'webapp2:5000'
       server3_url: 'webapp3:5000'
