---
- name: Install Nginx    # Название для роли
yum:    # Используемый модуль для установки приложения. В данном случае - это yum.
 name=nginx    # Название устанавливаемого пакета.
 state=latest    # Версия устанавливаемого пакета. Можно указать указать конкретную версию, в случае необходимости.
when:    # when - условие, при котором будет выполняться таска. В данном случае условием служит ОСь семейства красной шляпы.
 ansible_os_family == "RedHat"
notify:    # обработчик, который будет вызван в случае успешного выполнения задачи.
 - nginx systemd
